[package]
name = "exmex"
version = "0.11.4"  # check html document root in lib.rs and the Readme.md
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/exmex"
description = "fast, simple, and extendable mathematical expression evaluator able to compute partial derivatives"
repository = "https://github.com/bertiqwerty/exmex/"
homepage = "https://github.com/bertiqwerty/exmex/"
readme = "README.md"
keywords = ["math", "parser", "expression", "eval", "differentiation"]
categories = ["parser-implementations", "science"]
include = ["**/*.rs", "Cargo.toml"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
regex = "1"
num = "0.4"
smallvec = "1.6.1"
lazy_static = "1.4.0"
serde = { version="1", optional = true }

[profile.test]
opt-level = 3

[profile.release]
debug = true

[features]
value = []

[dev-dependencies]
rand = "0.8.4"
itertools = "0.10.1"
criterion = "0.3.4"
meval = "0.2.0"
fasteval = "0.2.4"
rsc = "2.0.0"
evalexpr = "6.4.0"
serde_test = "1"
serde_json = "1"

[[bench]]
name = "benchmark"
harness = false
