name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build without features
      run: cargo build --verbose
    - name: Build with serde and value
      run: cargo build --verbose --all-features
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --all-features
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        toolchain: nightly
        override: true
        components: clippy
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

