name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build without features
      run: cargo build --verbose
    - name: Build with serde and value
      run: cargo build --verbose --all-features
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose --all-features
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Install fuzz
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-fuzz 
    - name: Fuzz eval_str
      uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: run eval_str -- -runs=20000
    - name: Fuzz from_str
      uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: run --all-features from_str -- -runs=20000
    - name: Fuzz parse_val
      uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: run --all-features parse_val -- -runs=20000
