name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build without features
      run: cargo build --verbose
    - name: Build with serde and value
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
